# application.yml
app:
  version: 1.0.7

server:
  port: 8090

logging:
  level:
    root: INFO
    com.besl: INFO

spring:
  ai:
    ollama:
      chat:
        model: qwen3:14b
    ollama.base-url: http://localhost:11434

jmix:
  ui:
    view-file-extensions:
      - htm
      - html
      - jpg
      - png
      - jpeg
      - pdf

